# Generated by Django 2.2.4 on 2019-08-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reserve', to='users.Customer'),
        ),
    ]
