# Generated by Django 2.2.4 on 2019-08-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_assigngroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='registration_price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
