# Generated by Django 2.2.4 on 2019-08-17 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20190817_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Company'),
        ),
    ]
