# Generated by Django 2.2.4 on 2019-08-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_auto_20190817_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'Reserved'), ('A', 'Available')], default='A', max_length=1),
        ),
    ]
